### ISSUE TITLE
Discord Module Merger

### ISSUE THREAD

**Issue by ArchBlood** [GreenMeteor/auth-discord#2]
- [ ] [Discordapp Module](https://github.com/GreenMeteor/discordapp)
- [ ] [Preminum Discordapp Module](https://github.com/GreenMeteor/premium_discord)
- [ ] [Discord Auth Module](https://github.com/GreenMeteor/auth-discord)

**Comment by ArchBlood** [comment]
More tests needed to be done for some smaller bugs later tomorrow.

- [ ] Fix: Display widget only if fields are filled (*Dashboard* & *Space(s)*)
- [ ] Implement trigger for switching between dark & light version of the Discord widget, if possible, if not possible drop the option
